%% Clear workspace
% SIM results
clear exec_time start_time stop_time ticToc ...
    Fx Fy ...
    Mx My Mz ...
    Tgi Ts Ti ...
    p_out tAirInterne ...
    re rroul sa sr v ...
    kzz rnom...
    wear ppa deltap Nx Ny...
    TeqWLF Tc0 Tcm Tn Wf...
    pertes G Wg deport_y Pc0...
    Lx S2 D_MFD IntWMeca IntChim...
    mu0 partChim...
    Vx_i Vy_i p_i gamma_i Fz_i...
    omega T

% SIM parameters
clear solverMode calcOpt rep timeIni pIni tAirInterneIni tGi tiIni tsIni scalingFactor standStill fliptire imposedPressure wearDegradation deltaT steerAngle 

% Physical parameters
clear simulationName simulationInfo taille CamberAngle derive_max InclinAngle Mug muRoad Press Pressure SAa SAb SABase SAc SRBase SRinput Speed TAir TempAir TempTrack time tout TSol Vel_x Vel_y VerticalLoad Vx Vy