%% Save results
% Pour sauver les résulats de simulation dans un .mat global

i = 0;
while isfile(strcat('.\simResults\Results', int2str(i), '.mat'))
  % File exists.
  i = i+1;  
end

fileName = strcat('.\simResults\Results', int2str(i), '.mat');

save(fileName, ...
        'simulationName', 'simulationInfo',  'ticToc', 'exec_time', ...
        'Fx', 'Fy', ...
        'Mx', 'My', 'Mz', ...
        'Tgi', 'Ts', 'Ti', ...
        'p_out', 'tAirInterne', ...
        're', 'rroul', 'sa', 'sr', 'v', ...
        'kzz', 'rnom',...
        'wear', 'ppa','deltap','Nx','Ny',...
        'TeqWLF', 'Tc0', 'Tcm', 'Tn', 'Wf',...
        'pertes', 'G', 'Wg', 'deport_y', 'Pc0',...
        'Lx', 'S2', 'D_MFD', 'IntWMeca', 'IntChim',...
        'mu0', 'partChim', ...
        'tire_id')